name: PluginTemplate
version: '${version}'
main: gg.bitesize.template.Main
api-version: '26.3'
description: bitesize plugin template base
author: bitesize
website: https://bitesize.gg

libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:${kotlinVersion}
